fn main() {
    // Uncomment the appropriate line to point the queries generated by Autometrics
    // to the appropriate Prometheus instance.
    // Note that you will need to have Rust Analyzer reload the workspace for the change to take effect.
    // println!("cargo:rustc-env=PROMETHEUS_URL=https://prometheus.studio.fiberplane.com");
    // println!("cargo:rustc-env=PROMETHEUS_URL=https://prometheus.dev.fiberplane.io");
    // println!("cargo:rustc-env=PROMETHEUS_URL=https://prometheus.demo.fiberplane.io");
}
